### ISSUE TITLE
:: is already used in css

### ISSUE THREAD

**Issue by asafigan** [eveningkid/pretty-components#1]
:: is already used in css for sudo elements. What happens when new sudo elements are added to the css spec?

**Comment by eveningkid** [comment]
I agree on this. Actually, behind the scene, *::* will be converted to *_*. 
Meaning that if using *::* seems like a problem for now, you can replace it by *_*.

Also, if you have any other idea on how this should be written instead, I'm really open to suggestions. :)

**Comment by asafigan** [comment]
how do you prevent things like `::before` from being transformed to `_before`?

**Comment by eveningkid** [comment]
It's using sass syntax so if you want to use `::before`, you need to use the `&` sign such as `&::before`.

**Comment by asafigan** [comment]
Oh, so `::before` would get transformed to `_before`, but only selectors that have only `::`. Would `div > ::before` be transformed?

**Comment by eveningkid** [comment]
My bad, here is the current implementation, inside [`pretty-components-formatter`](https://github.com/eveningkid/pretty-components-formatter/blob/master/src/parse-pss.js#L36):
```js
if (
  line.includes('::')
  && !line.includes('after')
  && !line.includes('before')
) {
  lines[index] = line.replace('::', '_');
}

if (lines[index].trim().charAt(0) === ':' && depth === 2) {
  lines[index] = lines[index].replace(':', '_');
}
```
So, for your question, no, `div > ::before` wouldn't be transformed.

**Comment by asafigan** [comment]
I would suggest doing something consistent rather than having special cases. I would either only transform rules that are only `::something` or using the `_something` syntax. Because the way it's done now, the code base has to be updated when new sudo elements are added, which could break existing code in people's projects. Also the current way doesn't allow people to use the variable or value `before` and `after`, which can be confusing and frustrating.

**Comment by asafigan** [comment]
Also `before` and `after` are not the only currently available sudo elements. Here is the full list: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements. Also there are some vendor prefixed sudo elements like `::-moz-selection` https://developer.mozilla.org/en-US/docs/Web/CSS/::selection.

**Comment by eveningkid** [comment]
Fair point. Thank you for all these details, I totally agree with you on this.

Now back to your suggestions:
> I would either only transform rules that are only ::something   

If so, then you still need to hardcode every available pseudo elements, which as you mentioned, would break people's code.

> or using the _something syntax.

At first, I switched to "::" because I thought people would actually say that using "_something" doesn't feel css enough.

---
To be honest, I feel that this kind of decision is hard to make as in both ways, some people will always disagree. 

The perfect way would be to introduce another character such as ":" to mention prop-related styles.

**Comment by asafigan** [comment]
so `:` is used for sudo classes and `::` is used by sudo elements. You could do `:::`, but might be hard to read. `_` is non offensive to me. It is also not a valid css selector (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors), which means that there will be no conflict on the existing css spec.

**Comment by asafigan** [comment]
You could also make it configurable. Say you make the symbol `_`, you could have the webpack loader have an argument that accepts an array of alternatives so that people can use what they want. Silly example `(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧`.

**Comment by eveningkid** [comment]
This is a good suggestion. 
I think I'll focus on the syntax more than to what it fallbacks to.
I'll definitely keep your idea in mind, thanks a lot Andrew.
Have a nice day. :)
