### ISSUE TITLE
How to apply media queries?

### ISSUE THREAD

**Issue by ekafyi** [eveningkid/pretty-components#3]
Hello again. I went through the repo and your Medium posts but could not find any info — how do we create media queries in .pss?

This is what I tried:

```
// Button.pss
Button {
  color: red;
}
@media screen and (min-width: 768px) {
  Button {
    color: green;
  }
}
```
But it compiles incorrectly to:
```
<style>
.Button @media screen and (min-width: 768px) .Button{color: green;}
</style>
```

Would appreciate your help.
Thanks (again)!

**Comment by eveningkid** [comment]
This repo is only for `pretty-components`, not for `pss-lang`.
I think that with that version, I'm not sure that media queries are handled.

If you use `pss-loader`, you should be able to do it writing the following:
```sass
button.Button {
  color: red;
  
  @media screen and (min-width: 768px) {
    color: green;
  }
}
```

But for your question, I'm afraid it's not implemented with pretty components. 😞

I invite you to use [pss-loader](https://github.com/eveningkid/pss-loader) instead.

**Comment by ekafyi** [comment]
I tried **pss-loader** but unfortunately it does not suit my particular use case. I choose **pretty-components** is because it outputs legible, semantic CSS classes (`.button`, `.button--primary`) which can be easily extracted or even copy-pasted elsewhere. I'm building a component / quick prototyping library in React which will also need to be integrated with non-React web app (Go with Mustache HTML & SCSS front-end).

I perfectly understand though. Again, thanks for responding!
